# The path to the model checkpoint for the source agent
# Note: The agent determines the environment
# Note: The type of observation of the policy matters, as inpainting will not run if the observation is lowdim
source_agent_path: can_low_dim/20240123025005/models/model_epoch_250_PickPlaceCan_success_1.0.pth

# Similar to source_agent_path, but for the target agent (typically both are the same)
target_agent_path: can_low_dim/20240123025005/models/model_epoch_250_PickPlaceCan_success_1.0.pth

# Number of rollouts done for evaluation
n_rollouts: 1

# Max horizon for each rollout 
horizon: 350
seed: 0

# Keep true for now
passive: True

# Allows for using sockets to connect the source robot process and target robot process
# Ensure that this is true for now until the communication backend is being reworked.
connection: True

# The types of the source and target robot respectively (Panda, Sawyer, UR5e, Kinova3, Jaco, IIWA)
source_robot_name: "Panda"
target_robot_name: "UR5e"

# Tracking error thresholds are for when absolute control is used, i.e. 
# The controller steps the robot end effector to within tracking_error for the target pose
# There is also a limit on the maximum number of internal iterations, which is num_iter_max
# Typically the tracking error and num_iter_max are the same for both source and target
# Note: if num_iter_max is set to 1, then this is non-blocking control, blocking control otherwise
source_tracking_error_threshold: 0.015
source_num_iter_max: 300

target_tracking_error_threshold: 0.015
target_num_iter_max: 300

# If set to true, control type will be delta as opposed to absolute
delta_action: false

# Inpainting related configuration
# The conditions to enable it are
# 1) The policy is highdim
# 2) enable_inpainting is set to true
# 3) (Currently, ros mode is the only publicly support mode). Set use_ros to true
# 4) Set offline_eval to False (for now until better documentation is put up to support that mode)
# 5) Set diffusion parameters accordingly
enable_inpainting: false
use_ros: false
offline_eval: false

use_diffusion: false

# Diffusion types are still being worked on for public release, so for now, set to ""
diffusion_input_type: ""

# Set to path for a folder containing both source.txt and target.txt results
results_folder: "results"

# Optionally, can provide a path for storing videos of the rollouts for both types
# Uncomment below if necessary
# source_video_path: "source_video.mp4"
# target_video_path: "target_video.mp4"

# Optionally, provide different gripper types to evaluate
# If left commented, it will just default to the normal gripper each robot uses.
# Gripper types can be PandaGripper, RobotiqGripper, or default
# source_gripper_type: "default"
# target_gripper_type: "default"