[tool.black]
# https://github.com/psf/black
line-length = 88
target-version = ["py310"]
exclude = "(.eggs|.git|.hg|.mypy_cache|.nox|.tox|.venv|.svn|_build|buck-out|build|dist)"

[tool.isort]
profile = "black"
line_length = 88
force_sort_within_sections = "True"
order_by_type = "False"
