name: Build Sphinx Documentation

on:
  push:
    branches:
      - main  # You can change this to whatever branch you want to trigger the build
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: xembody

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.18'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]

    - name: Build Documentation
      run: |
        make -C docs/ html  # Assuming your Sphinx documentation is located in a directory named "docs"

    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/build/html
